deployment:
  imagePullPolicy: IfNotPresent
  image: lycheeorg/lychee
  strategy: Recreate
  annotations:
  tag:

sizeUploadPVC: 100Gi
storageclass: longhorn
timezone: Europe/Berlin
ingressClassName: traefik
host: lychee.example.com

admin:
  username: admin
  password: admin

db:
  connection: postgres
  database: lychee
  host:
  port:
  username:
  password:
