appName: lychee
timezone: Europe/Berlin
dbConnection: sqlite
host: lychee.example.com

ingress:
  className: traefik
  #annotations:
    #cert-manager.io/cluster-issuer: letsencrypt

deployment:
  imagePullPolicy: IfNotPresent
  image: lycheeorg/lychee
  strategy: Recreate
  annotations:
  tag:

uploads:
  size: 100Gi
  storageClass: longhorn

conf:
  size: 5Gi
  storageClass: longhorn

admin:
  username: admin
  password: admin

additionalEnvs: []
secretRefs: []
