deployment:
  imagePullPolicy: IfNotPresent
  image: lycheeorg/lychee
  strategy: Recreate
  annotations:
  tag:

sizeUploadPVC: 100Gi
storageclass: longhorn
timezone: Europe/Berlin
ingressClassName: traefik
host: lychee.example.com

admin:
  username: admin
  password: admin

db:
  connection: postgres
  host:
  port:

secretRefs:
- name: DB_DATABASE
  key: db
  secretName: db-credentials
- name: DB_USERNAME
  key: user
  secretName: db-credentials
- name: DB_PASSWORD
  key: password
  secretName: db-credentials

