---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.deployment.annotations }}
  annotations:
{{ toYaml .Values.deployment.annotations | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 1
  strategy:
    type: {{ .Values.deployment.strategy }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.deployment.image }}:{{ default .Chart.AppVersion .Values.deployment.tag }}
        imagePullPolicy: {{ .Values.deployment.imagePullPolicy }}
        volumeMounts:
        - name: uploads
          mountPath: /uploads
        ports:
        - containerPort: 80
          name: http
        env:
        - name: APP_URL
          value: https://{{ .Values.host }}
        - name: TIMEZONE
          value: {{ .Values.timezone }}
        - name: PHP_TZ
          value: {{ .Values.timezone }}
        - name: ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}
              key: adminUser
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Chart.Name }}
              key: adminPassword
        {{- range .Values.additionalEnvs }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        - name: DB_CONNECTION
          value: {{ .Values.db.connection }}
        - name: DB_HOST
          value: {{ .Values.db.host }}
        - name: DB_PORT
          value: {{ .Values.db.port | quote }}
        {{- range .Values.secretRefs }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              key: {{ .key }}
              name: {{ .secretName }}
        {{- end }}
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: {{ .Chart.Name }}-uploads
