{{- if eq "sqlite" .Values.dbConnection }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Chart.Name }}-database
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.size }}
  storageClassName: {{ .Values.database.storageClass }}
{{- end }}
