---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  dbUsername: {{ .Values.db.username }}
  dbPassword: {{ .Values.db.password }}
  adminUser: {{ .Values.admin.username }}
  adminPassword: {{ .Values.admin.password }}
