---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: {{ .Chart.Name }}
